global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'merklith-node-1'
    static_configs:
      - targets: ['merklith-node-1:9090']
    metrics_path: /metrics

  - job_name: 'merklith-node-2'
    static_configs:
      - targets: ['merklith-node-2:9090']
    metrics_path: /metrics

  - job_name: 'merklith-node-3'
    static_configs:
      - targets: ['merklith-node-3:9090']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
